package com.app.pojos;

import javax.persistence.*;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Entity
@Table(name="admin_tbl")
@NoArgsConstructor
@AllArgsConstructor
@Data
public class Admin extends BaseEntity{

	//properties name should be same or usejsonproperty annotation to match it 
	//automatically 
	//add autogenerated if for the time being 
	@Id
	private String id;
}
